version: 3.9
services:
  webscraping:
  # will build ./docker/webscraping/Dockerfile
    build: ./docker/webscraping
    ports: 
    - "5000:5000"
  neural-net:
  # will build ./docker/neural-net/Dockerfile
    build: ./docker/neural-net
    ports:
    - "8080:8080"
  redis:
    image: "redis:alpine"