version: "3.9"
services:
  webscraping:
  # will build ./docker/webscraping/Dockerfile
    build: ./webscraping
    ports: 
    - "5000:5000"
  neural-net:
  # will build ./docker/neural-net/Dockerfile
    build: ./neural-net
    ports:
    - "8080:8080"
  data-cleaning:
  # will build ./docker/data-cleaning/Dockerfile
    build: ./data-cleaning
    ports:
    - "5050:5050"
  redis:
    image: "redis:alpine"